config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    resources :products
    resources :carts
    resources :orders
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    namespace :admins do
      post "/products/get_products_active", to: "products#get_products_active"
      root to: "products#index"
      resources :products
      resources :orders
      resources :users
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
  VALID_EMAIL_REGEX = Settings.email_regex
  PERMIT_SIGNUP_ATTRIBUTES = %i(name email password password_confirmation)
                             .freeze
  PERMIT_CREATE_ATTRIBUTES = %i(name email password password_confirmation role)
                             .freeze

  validates :name, presence: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}

  before_save :downcase_email

  enum role: {user: 0, admin: 1, support: 2, logistic: 3}, _suffix: true

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminsController
  before_action :find_user, only: %i(show edit update destroy)

  def index
    @search = User.ransack(params[:q])
    @users = @search.result
                    .page(params[:page])
                    .per(Settings.per_page)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t ".user_created_success"
      redirect_to admins_users_path
    else
      flash[:danger] = t ".user_create_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t ".user_updated"
      redirect_to [:admins, @user]
    else
      flash[:danger] = t ".user_update_fail"
      render :edit
    end
  end

  def show; end

  def destroy
    if @user.destroy
      flash[:success] = t ".user_deleted"
      redirect_to admins_users_path
    else
      flash[:danger] = t ".user_delete_fail"
      redirect_to root_path
    end
  end

  private

  def find_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t ".unknown_user"
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit User::PERMIT_CREATE_ATTRIBUTES
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :load_user_by_email, only: :create

  def new; end

  def create
    if @user.is_blocked?
      flash[:error] = t ".blocked_account"
      redirect_to login_path
    else
      super
    end
  end

  private

  def load_user_by_email
    @user = User.find_by email: params[:user][:email].downcase
    return if @user

    flash[:error] = t "users.not_found"
    redirect_to request.referer || root_url
  end

  def after_sign_in_path_for _resource
    session[:forwarding_url] || root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t ".succeed_signup"
      redirect_to root_url
    else
      flash[:warning] = t ".failed_signup"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit User::PERMIT_ATTRIBUTES
  end
end

app/views/admins/users/_form.html.erb
<%= render "admins/shared/error_messages", object: @user %>
<%= form_for [:admins, @user] do |f| %>
  <div class="form-group row">
    <%= f.label :name, t(".name"), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: t(".placeholder_name") %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, t(".email"), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", placeholder: t(".placeholder_email") %>
    </div>
  </div>
  <% if action_name == "new" %>
    <div class="form-group row">
      <%= f.label :password, t(".password"), class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control", placeholder: t(".placeholder_password") %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :role, t(".role"), class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :role, options_for_select(option_role_select, @user.role), {}, {class: "form-control"} %>
    </div>
  </div>

  <div class="row">
    <div class="col d-flex justify-content-end">
      <button type="submit" class="btn btn-success"><%= t ".save" %></button>
    </div>
  </div>
  <br>
<% end %>

app/views/admins/users/_form_search.html.erb
<%= search_form_for @search, url: admins_users_path do |f| %>
  <div class="row">
    <div class="form-group col-3">
      <%= f.label "name", t(".name") %>
      <%= f.text_field :name_cont, placeholder: t(".placeholder_name", attr: t(".placeholder_name")), value: params[:q].try(:[], :name_cont), class: "form-control" %>
    </div>
    <div class="form-group col-3">
      <%= f.label "email", t(".email") %>
      <%= f.text_field :email_eq, placeholder: t(".placeholder_email", attr: t(".placeholder_email")), value: params[:q].try(:[], :email_eq), class: "form-control" %>
    </div>
    <div class="form-group col-3">
      <%= f.label "role_eq", t(".role") %>
      <%= f.select :role_eq, options_for_select(option_role_select_search, params[:q].try(:[], :role_eq)), {include_blank: t(".choose_role")}, {class: "form-control"} %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col d-flex justify-content-end">
      <%= link_to t(".reset"), admins_users_path, class: "btn btn-default" %>
      <button type="submit" class="btn btn-success"><%= t ".search" %></button>
    </div>
  </div>
<% end %>

app/views/admins/users/_item.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td>
    <div class="btn-group dropbottom">
      <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= t ".action" %>
      </button>
      <div class="dropdown-menu">
        <%= link_to t(".show"), admins_user_path(user), class: "dropdown-item" %>
        <%= link_to t(".edit"), edit_admins_user_path(user), class: "dropdown-item" %>
        <%= button_to t(".delete"), admins_user_path(user), method: :delete, data: {confirm: t(".you_sure?")}, class: "bg-none border-none padding-l-24" %>
      </div>
    </div>
  </td>
</tr>

app/views/admins/users/edit.html.erb
<main>
  <div class="container-fluid">
    <div class="mt-4">
      <%= link_to t(".back"), admins_users_path, class: "btn btn-success" %>
      <br>
      <br>
      <h1><%= t ".edit_user" %></h1>
      <br>
    </div>
    <%= render "admins/users/form" %>
  </div>
</main>

app/views/admins/users/index.html.erb
<main>
  <div class="container-fluid">
    <h1 class="mt-4"><%= t".list_users" %></h1>
    <%= render "admins/users/form_search" %>
    <br>
    <div class="card mb-4">
      <div class="card-body">
        <div class="table-responsive">
          <h6 class="text-right">
            <span><%= t ".counts" %><%= @users.total_count %></span>
          </h6>
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th><%= t ".name" %></th>
              <th><%= t ".email" %></th>
              <th><%= t ".role" %></th>
              <th><%= t ".action" %></th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: "admins/users/item", collection: @users, as: :user %>
            <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
              </div>
            </div>
            </tbody>
          </table>
          <%= paginate @users, theme: "twitter-bootstrap-4" %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/admins/users/new.html.erb
<main>
  <div class="container-fluid">
    <div class="mt-4">
      <%= link_to t(".back"), admins_users_path, class: "btn btn-success" %>
      <br>
      <br>
      <h1><%= t ".create_user" %></h1>
      <br>
    </div>
    <%= render "admins/users/form" %>
  </div>
</main>

app/views/admins/users/show.html.erb
<main>
  <div class="container-fluid">
    <div class="mt-4">
      <%= link_to t(".back"), admins_users_path, class: "btn btn-success" %>
      <br>
      <br>
      <h1><%= t ".user_detail" %></h1>
      <br>
    </div>
    <dl class="row">
      <dt class="col-sm-3"><%= t ".name" %></dt>
      <dd class="col-sm-9">
        <%= @user.name %>
      </dd>
      <dt class="col-sm-3"><%= t ".email" %></dt>
      <dd class="col-sm-9">
        <%= @user.email %>
      </dd>
      <dt class="col-sm-3"><%= t ".role" %></dt>
      <dd class="col-sm-9">
        <%= @user.role %>
      </dd>
    </dl>
  </div>
</main>