config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    resources :products
    resources :carts
    resources :orders
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    namespace :admins do
      post "/products/get_products_active", to: "products#get_products_active"
      root to: "products#index"
      resources :products
      resources :orders
      resources :users
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper

  before_action :declare, :check_exist, :create_sessions_cart,
                :update_sessions_cart, only: :create

  def index
    return unless session[:cart]

    @carts = Product.filter_by_ids(load_product_ids)
                    .includes :images
    @total = session[:cart].map do |item|
      item["quantity"].to_i * Product.find_by(id: item["product_id"]).price
    end.sum
  end

  def create
    render json: {
      sessions_length: session[:cart].length,
      total_item: @total_item,
      total: @total
    }
  end

  def update; end

  private

  def declare
    @exist = false
    @total_item = 0
    @total = 0
  end

  def check_exist
    session[:cart]&.each do |item|
      @exist = true if item["product_id"].to_i == params[:product_id].to_i
      product = Product.find_by id: item["product_id"]
      @total += product.price * item["quantity"]
    end
  end

  def create_sessions_cart
    return if @exist

    session[:cart] ||= []
    session[:cart].push(product_id: params[:product_id].to_i,
                        quantity: Settings.quantity_one)
  end

  # rubocop:disable Metrics/AbcSize

  def update_sessions_cart
    return unless @exist

    session[:cart].map do |item|
      next unless item["product_id"].to_i == params[:product_id].to_i

      product = Product.find_by id: params[:product_id]
      case params[:option]
      when "dec"
        @total -= product.price
        item["quantity"] -= 1 if item["quantity"] > 1
        @total_item = product.price * item["quantity"]
        session[:cart].delete(item) if item["quantity"] == 1
      when "inc"
        item["quantity"] = item["quantity"] + 1
        @total_item = product.price * item["quantity"]
        @total += product.price
      when "del"
        @total_item = product.price * item["quantity"]
        @total -= total_item
        session[:cart].delete(item)
      end
    end
  end
  # rubocop:enable Metrics/AbcSize

  def load_product_ids
    product_ids = []
    session[:cart].sort_by!{|k| k["product_id"].to_i}
    session[:cart].each{|item| product_ids << item["product_id"]}
    product_ids
  end

  def user_params
    params.require(:user).permit User::PERMIT_ATTRIBUTES
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def option_status_order_update
    Order.statuses.map do |value, _key|
      [I18n.t("admins.orders.form_search.#{value}"), value]
    end
  end

  def option_status_order_search
    Order.statuses.map do |value, key|
      [I18n.t("admins.orders.form_search.#{value}"), key]
    end
  end

  def option_status_product
    Product.statuses.map do |value, key|
      [I18n.t("admins.products.form_search.#{value}"), key]
    end
  end

  def active_treeview_menu treeview_items, type = :class
    match_items = request.path.split("/")
    return unless match_items.include? treeview_items

    type
  end
end

app/views/carts/_banner.html.erb
<section class="breadcrumb-section set-bg" data-setbg="https://i.ibb.co/Rgd8vnb/breadcrumb.jpg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="breadcrumb__text">
          <h2><%= yield :title %></h2>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/carts/_header.html.erb
<section class="hero hero-normal">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="hero__categories">
          <div class="hero__categories__all">
            <i class="fa fa-bars"></i>
            <span><%= t "layouts._header.categories" %></span>
          </div>
          <ul>
            <% @categories.each do |category| %>
              <li>
                <%= link_to products_path(category_id: category.id) do %>
                  <%= category.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="hero__search">
          <div class="hero__search__form">
            <%= form_tag products_path, method: :get do %>
              <%= text_field_tag "keyword", nil, placeholder: t("layouts._header.key_word") %>
              <%= button_tag t("layouts._header.search"), name: nil, class: "site-btn" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/carts/_item.html.erb
<% if session[:cart] %>
  <tr id="row-product-id-<%= item.id %>">
    <td class="shoping__cart__item">
      <%= image_tag item.images.first.url, class:"w-25" %>
      <h5><%= item.name %></h5>
    </td>
    <td class="shoping__cart__price">
      <%= number_to_currency item.price %>
    </td>
    <td class="shoping__cart__quantity">
      <div class="quantity">
        <div class="pro-qty update-cart" data-product-id="<%= item.id %>">
          <%= text_field_tag nil, session[:cart][item_counter] ? session[:cart][item_counter]["quantity"]: "", disabled: true %>
        </div>
      </div>
    </td>
    <td class="shoping__cart__total" id="quantity-product-id-<%= item.id %>">
      <% if session[:cart][item_counter] %>
        <%= number_to_currency item.price * session[:cart][item_counter]["quantity"] %>
      <% end %>
    </td>
    <td class="shoping__cart__item__close delete-cart-item" data-product-id="<%= item.id %>" >
      <span class="icon_close"></span>
    </td>
  </tr>
<% end %>

app/views/carts/index.html.erb
<%= provide :title, t(".carts") %>
<%= render "header" %>
<%= render "banner" %>
<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad">
  <div class="container">
    <% if session[:cart] %>
      <div class="row">
        <div class="col-lg-12">
          <div class="shoping__cart__table">
            <table>
              <thead>
                <tr>
                  <th class="shoping__product"><%= t ".product" %></th>
                  <th><%= t ".price" %></th>
                  <th><%= t ".quantity" %></th>
                  <th><%= t ".total" %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "carts/item", collection: @carts, as: :item %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-lg-6">
        <div class="shoping__cart__btns">
          <%= link_to t(".continue_shopping"), products_path, class: "primary-btn cart-btn" %>
        </div>
      </div>
      <% if session[:cart] %>
        <div class="col-lg-6">
          <div class="shoping__checkout">
            <h5><%= t ".cart_total" %></h5>
            <ul>
              <li><%= t ".total" %> <span id="total"><%= number_to_currency @total %></span></li>
            </ul>
            <%= link_to new_order_path, class: "primary-btn" do %>
              <%= t ".checkout" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- Shoping Cart Section End -->