config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    devise_for :users
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    resources :products
    resources :carts
    resources :orders
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    namespace :admins do
      post "/products/get_products_active", to: "products#get_products_active"
      root to: "products#index"
      resources :products
      resources :orders
      resources :users
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer Section Begin -->
<footer class="footer spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="footer__about">
          <div class="footer__about__logo">
            <a href="./index.html">
              <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/logo_i3t2tp.png") %>
            </a>
          </div>
          <ul>
            <li>Address: 60-49 Road 11378 New York</li>
            <li>Phone: +65 11.188.888</li>
            <li>Email: hello@colorlib.com</li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
        <div class="footer__widget">
          <h6>Useful Links</h6>
          <ul>
            <li><a href="#">About Us</a></li>
            <li><a href="#">About Our Shop</a></li>
            <li><a href="#">Secure Shopping</a></li>
            <li><a href="#">Delivery infomation</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Our Sitemap</a></li>
          </ul>
          <ul>
            <li><a href="#">Who We Are</a></li>
            <li><a href="#">Our Services</a></li>
            <li><a href="#">Projects</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Innovation</a></li>
            <li><a href="#">Testimonials</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-12">
        <div class="footer__widget">
          <h6>Join Our Newsletter Now</h6>
          <p>Get E-mail updates about our latest shop and special offers.</p>
          <form action="#">
            <input type="text" placeholder="Enter your mail">
            <button type="submit" class="site-btn">Subscribe</button>
          </form>
          <div class="footer__widget__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-pinterest"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="footer__copyright">
          <div class="footer__copyright__payment">
            <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/payment-item_pgd60u.png") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

app/views/layouts/_header.html.erb
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
  <div class="humberger__menu__logo">
    <%= link_to home_path do %>
      <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/logo_i3t2tp.png") %>
    <% end %>
  </div>
  <div class="humberger__menu__cart">
    <ul>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-heart"></i>
          <span>1</span>
        <% end %>
      </li>
      <li>
        <%= link_to carts_path do %>
          <i class="fa fa-shopping-bag"></i>
          <span class="length-cart">
            <%= session[:cart].length if session[:cart]%>
          </span>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="humberger__menu__widget">
    <div class="header__top__right__language">
      <%= image_tag(Settings.language_image, class: "") %>
      <div><%= I18n.locale %></div>
      <span class="arrow_carrot-down"></span>
      <ul>
        <li><%= link_to t("layouts._header.vietnamese"), locale: "vi" %></li>
        <li><%= link_to t("layouts._header.english"), locale: "en" %></li>
      </ul>
    </div>
    <div class="header__top__right__auth">
      <% if user_signed_in? %>
        <li class="dropdown li-none">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
            <%= current_user.name %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li class="divider"></li>
            <%= link_to t("layouts._header.logout"), destroy_user_session_path, method: :delete %>
            <li class="divider"></li>
            <%= link_to t("layouts._header.edit_account"), edit_user_registration_path %>
            <% if current_user.admin_role?  %>
              <li class="divider"></li>
              <%= link_to t("layouts._header.enter_admin"), admins_root_path %>
            <% end %>
          </ul>
        </li>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-user"></i>
          <%= t "layouts._header.login" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <nav class="humberger__menu__nav mobile-menu">
    <ul>
      <li class="active">
        <%= link_to t("layouts._header.home"), home_path %>
      </li>
      <li>
        <%= link_to t("layouts._header.products"), products_path %>
      </li>
      <li>
        <%= link_to t("layouts._header.help"), help_path %>
      </li>
    </ul>
  </nav>
  <div id="mobile-menu-wrap"></div>
  <div class="header__top__right__social">
    <%= link_to "#" do %>
      <i class="fa fa-facebook"></i>
    <% end %>
    <%= link_to "#" do %>
      <i class="fa fa-twitter"></i>
    <% end %>
    <%= link_to "#" do %>
      <i class="fa fa-linkedin"></i>
    <% end %>
    <%= link_to "#" do %>
      <i class="fa fa-pinterest-p"></i>
    <% end %>
  </div>
</div>
<!-- Humberger End -->

<!-- Header Section Begin -->
<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <div class="header__top__right__social">
              <%= link_to "#" do %>
                <i class="fa fa-facebook"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fa fa-twitter"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fa fa-linkedin"></i>
              <% end %>
              <%= link_to "#" do %>
                <i class="fa fa-pinterest-p"></i>
              <% end %>
            </div>
            <div class="header__top__right__language">
              <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/language_uyra3n.png") %>
              <div><%= I18n.locale %></div>
              <span class="arrow_carrot-down"></span>
              <ul>
                <li><%= link_to t("layouts._header.vietnamese"), locale: "vi" %></li>
                <li><%= link_to t("layouts._header.english"), locale: "en" %></li>
              </ul>
            </div>
            <div class="header__top__right__auth">
              <% if user_signed_in? %>
                <li class="dropdown li-none">
                  <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
                    <%= current_user.name %>
                    <b class="caret"></b>
                  <% end %>
                  <ul class="dropdown-menu">
                    <li class="divider"></li>
                    <%= link_to t("layouts._header.logout"), destroy_user_session_path, method: :delete %>
                    <li class="divider"></li>
                    <%= link_to t("layouts._header.edit_account"), edit_user_registration_path %>
                    <% if current_user.admin_role?  %>
                      <li class="divider"></li>
                      <%= link_to t("layouts._header.enter_admin"), admins_root_path %>
                    <% end %>
                  </ul>
                </li>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="fa fa-user"></i>
                  <%= t "layouts._header.login" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="header__logo">
          <%= link_to home_path do %>
            <%= image_tag("https://res.cloudinary.com/tdh/image/upload/v1595343877/images/logo_i3t2tp.png") %>
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <nav class="header__menu">
          <ul>
            <li class="<%= active_treeview_menu "home", "active" %>" >
              <%= link_to t("layouts._header.home"), home_path %>
            </li>
            <li class="<%= active_treeview_menu "products", "active" %>">
              <%= link_to t("layouts._header.shop"), products_path %>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-lg-3">
        <div class="header__cart">
          <ul>
            <li>
              <%= link_to carts_path do %>
                <i class="fa fa-shopping-bag"></i>
                <span class="length-cart">
                  <%= session[:cart].length if session[:cart] %>
                </span>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="humberger__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>
<!-- Header Section End -->

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "admins/admins", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "admins/font-awesome-all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "admins", "data-turbolinks-track": "reload" %>
  </head>
  <body class="sb-nav-fixed">
    <%= render "admins/layouts/navbar" %>
    <div id="layoutSidenav">
      <%= render "admins/layouts/sidenav" %>
      <div id="layoutSidenav_content">
        <% flash.each do |message_type, message| %>
          <div id="alert-message" class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <%= yield %>
        <%= render "admins/layouts/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="toast custom-toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2000">
      <div class="toast-body">
        <%= t ".updated_cart" %>
      </div>
    </div>

    <% flash.each do |message_type, message| %>
      <div id="alert-message" class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </body>
</html>